---
title: "Save filter as .csv for use in Phyton"
author: "Amy van der Ham"
date: "12/06/2021"
output: html_document
editor_options: 
  chunk_output_type: console
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
# load final filter 
final_filter <- readRDS("/Users/amyvanderham/Documents/Research_Assistant_Rgit/veni_sysrev/amy/final_filter.RData")

# save as .csv
write.csv(final_filter,"/Users/amyvanderham/Documents/Research_Assistant_Rgit/veni_sysrev/amy/try_outs/final_filter.csv", row.names = FALSE)

# load bigrams filter
bigrams_filter <- readRDS("/Users/amyvanderham/Documents/Research_Assistant_Rgit/veni_sysrev/amy/bigrams_filter.RData")

# save as .csv
write.csv(bigrams_filter,"/Users/amyvanderham/Documents/Research_Assistant_Rgit/veni_sysrev/amy/try_outs/bigrams_filter.csv", row.names = FALSE)
```


```{r}
# load pretrained word2vec 
wrd2vec_embedding <- read.csv("/Users/amyvanderham/Documents/Research_Assistant_Rgit/veni_sysrev/amy/try_outs/pretrained_w2v_filtered.csv", header = FALSE)

# adjust the first column name to word
colnames(wrd2vec_embedding)[1] <- "word"

# check structure of dataframe
str(wrd2vec_embedding)

# remove certain characters from the column V2 which now is column of the type character and contains a string as value. 
library(tidyverse)
# create new data frame that can be used for applying adjustments
df_w2vemb <- wrd2vec_embedding

# remove the [ character from V2 
df_w2vemb$V2 <-gsub("\\[","",as.character(df_w2vemb$V2))

# remove the ] character from V2 
df_w2vemb$V2 <-gsub("\\]","",as.character(df_w2vemb$V2))

# remove the \n character from V2 
df_w2vemb$V2 <-gsub("\\\n","",as.character(df_w2vemb$V2))

# check if removing the characters went correctly 
df_w2vemb[1,c("word", "V2")]
# -> yes there are now only numbers (the vectors)


# split column V2 into multiple columns
library(splitstackshape)
# separate on the space
df_w2vemb <- cSplit(df_w2vemb, "V2", " ")

# retain dimensions of data frame
dim(df_w2vemb)
# -> we have 10043 words that are defined by 300 dimensions.

# check values after splitting
df_w2vemb[1,]
# -> looks the same as before 

# check how many unique words there are
length(unique(df_w2vemb$word))
# -> as expected there are as many unique words as there are observations. 

# rename the column names of the data frame.
# First column is named word and the other columns dim1-40
colnames(df_w2vemb) <- c("word", paste0("dim", 1:300))

# check if there are any missings
summary(df_w2vemb)
# -> no missing values. 
```

# compare w2v with glove embedding
```{r}
w2v_embedding <- df_w2vemb

glove_embedding <-  readRDS("/Users/amyvanderham/Documents/Research_Assistant_Rgit/veni_sysrev/amy/try_outs/glove_embedding_final.RData")

glv_embedding <- as.data.frame(glove_embedding)

# check words that are in the glove embedding that are also in the w2v embedding
words_same <- subset(glv_embedding, rownames(glv_embedding) %in% wrd2vec_embedding$word)

# check words that are in the glove embedding but not in the w2vec embedding 
words_diff <- subset(glv_embedding, !(rownames(glv_embedding) %in% wrd2vec_embedding$word))

# check words that are in the w2v embedding but not in the glove embedding
words_in_w2v_notglve <- subset(w2v_embedding, !( word %in% rownames(glv_embedding)))
```

