---
title: "Save filter as .csv for use in Phyton"
author: "Amy van der Ham"
date: "12/06/2021"
output: html_document
editor_options: 
  chunk_output_type: console
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
# load final filter 
final_filter <- readRDS("/Users/amyvanderham/Documents/Research_Assistant_Rgit/veni_sysrev/amy/final_filter.RData")

# save as .csv
write.csv(final_filter,"/Users/amyvanderham/Documents/Research_Assistant_Rgit/veni_sysrev/amy/try_outs/final_filter.csv", row.names = FALSE)

# load bigrams filter
bigrams_filter <- readRDS("/Users/amyvanderham/Documents/Research_Assistant_Rgit/veni_sysrev/amy/bigrams_filter.RData")

# save as .csv
write.csv(bigrams_filter,"/Users/amyvanderham/Documents/Research_Assistant_Rgit/veni_sysrev/amy/try_outs/bigrams_filter.csv", row.names = FALSE)
```


```{r}
# load pretrained word2vec 
wrd2vec_embedding <- read.csv("/Users/amyvanderham/Documents/Research_Assistant_Rgit/veni_sysrev/amy/try_outs/pretrained_w2v_filtered.csv", header = FALSE)

# adjust the first column name to word
colnames(wrd2vec_embedding)[1] <- "word"

# check structure of dataframe
str(wrd2vec_embedding)

# remove certain characters from the column V2 which now is column of the type character and contains a string as value. 
library(tidyverse)
# create new data frame that can be used for applying adjustments
df_w2vemb <- wrd2vec_embedding

# remove the [ character from V2 
df_w2vemb$V2 <-gsub("\\[","",as.character(df_w2vemb$V2))

# remove the ] character from V2 
df_w2vemb$V2 <-gsub("\\]","",as.character(df_w2vemb$V2))

# remove the \n character from V2 
df_w2vemb$V2 <-gsub("\\\n","",as.character(df_w2vemb$V2))

# check if removing the characters went correctly 
df_w2vemb[1,c("word", "V2")]
# -> yes there are now only numbers (the vectors)

# split column V2 into multiple columns
library(splitstackshape)
# separate on the space
df_w2vemb <- cSplit(df_w2vemb, "V2", " ")

# retain dimensions of data frame
dim(df_w2vemb)
# -> we have 10043 words that are defined by 300 dimensions.

# check values after splitting
df_w2vemb[1,]
# -> looks the same as before 

# check how many unique words there are
length(unique(df_w2vemb$word))
# -> as expected there are as many unique words as there are observations. 

# rename the column names of the data frame.
# First column is named word and the other columns dim1-40
colnames(df_w2vemb) <- c("word", paste0("dim", 1:300))

# check if there are any missings
summary(df_w2vemb)
# -> no missing values. 

# save the embedding 
# convert the first column, word, to row index.
library(tidyverse)
w2v_embedding <- df_w2vemb %>%
     remove_rownames() %>%
     column_to_rownames(var = 'word')

# convert dataframe to a matrix
w2v_embedding <- as.matrix(w2v_embedding)
str(w2v_embedding)

# save the glove embedding to which the filter is applied so this can be easily loaded into other scripts
saveRDS(w2v_embedding, "/Users/amyvanderham/Documents/Research_Assistant_Rgit/veni_sysrev/amy/w2v_embedding.RData")
```

```{r}
# load pretrained word2vec with bigrams included
w2v_embedding_bigram <- read.csv("/Users/amyvanderham/Documents/Research_Assistant_Rgit/veni_sysrev/amy/try_outs/pretrained_w2v_filtered_bigrams.csv", header = FALSE)

# adjust the first column name to word
colnames(w2v_embedding_bigram)[1] <- "word"

# check structure of dataframe
str(w2v_embedding_bigram)

# remove certain characters from the column V2 which now is column of the type character and contains a string as value. 
library(tidyverse)
# create new data frame that can be used for applying adjustments
df_bigrams <- w2v_embedding_bigram

# remove the [ character from V2 
df_bigrams$V2 <-gsub("\\[","",as.character(df_bigrams$V2))

# remove the ] character from V2 
df_bigrams$V2 <-gsub("\\]","",as.character(df_bigrams$V2))

# remove the \n character from V2 
df_bigrams$V2 <-gsub("\\\n","",as.character(df_bigrams$V2))

# check if removing the characters went correctly 
df_bigrams[1,c("word", "V2")]
# -> yes there are now only numbers (the vectors)

# split column V2 into multiple columns
library(splitstackshape)
# separate on the space
df_bigrams <- cSplit(df_bigrams, "V2", " ")

# retain dimensions of data frame
dim(df_bigrams)
# -> we have 10068 words that are defined by 300 dimensions.

# check values after splitting
df_bigrams[1,]
# -> looks the same as before 

# rename the column names of the data frame.
# First column is named word and the other columns dim1-40
colnames(df_bigrams) <- c("word", paste0("dim", 1:300))

# check if there are any missings
summary(df_bigrams)
# -> no missing values. 

# save the embedding 
# convert the first column, word, to row index.
library(tidyverse)
w2v_bigrams_embedding <- df_bigrams %>%
     remove_rownames() %>%
     column_to_rownames(var = 'word')

# convert dataframe to a matrix
w2v_bigrams_embedding <- as.matrix(w2v_bigrams_embedding)
str(w2v_bigrams_embedding)

# save the glove embedding to which the filter is applied so this can be easily loaded into other scripts
saveRDS(w2v_bigrams_embedding, "/Users/amyvanderham/Documents/Research_Assistant_Rgit/veni_sysrev/amy/w2v_bigrams_embedding.RData")

# CREATE GLOVE EMBEDDING WITH BIGRAMS
# load existing word embeddings
# load glove vectors into R
vectors_glove <- data.table::fread('glove.840B.300d.txt', data.table = F,  encoding = 'UTF-8', quote="") 

# rename the columns
colnames(vectors_glove) <- c('word',paste('dim',1:300,sep = '_'))

# load data frame with column with selection of words to include in analysis. 
df_bigrams_glove <- readRDS("/Users/amyvanderham/Documents/Research_Assistant_Rgit/veni_sysrev/amy/bigrams_filter_glove.RData")

# create df in which only the words that we want to be included are kept
glove_embedding_bigrams <- subset(vectors_glove, word %in% df_bigrams_glove$filter_bigrams_glove)

# check number of unique words
length(unique((glove_embedding_bigrams$word)))
# 11619

# non-GloVe: check which words are in the filter but are not in the feature matrix and are therefore lost (unwanted).
lost_words <- subset(df_bigrams_glove, !(filter_bigrams_glove %in% glove_embedding_bigrams$word))
# 2182 words lost vs. 2117 words lost when token filter applied. 

length(unique((glove_embedding_bigrams$word))) + length(unique((lost_words$filter_bigrams_glove)))
# -> 27097. Which is equal to the line of code below. 
length(unique((df_bigrams_glove$filter_bigrams_glove)))


# transform so that it can be saved
glove_embedding_bigrams <- glove_embedding_bigrams %>%
     remove_rownames() %>%
     column_to_rownames(var = 'word')

# convert dataframe to a matrix
glove_embedding_bigrams <- as.matrix(glove_embedding_bigrams)
str(glove_embedding_bigrams)

saveRDS(glove_embedding_bigrams, "/Users/amyvanderham/Documents/Research_Assistant_Rgit/veni_sysrev/amy/try_outs/glove_embedding_bigrams.RData")
```

# compare w2v with glove embedding
```{r}
w2v_embedding <- df_w2vemb

glove_embedding <-  readRDS("/Users/amyvanderham/Documents/Research_Assistant_Rgit/veni_sysrev/amy/try_outs/glove_embedding_final.RData")

glv_embedding <- as.data.frame(glove_embedding)

# check words that are in the glove embedding that are also in the w2v embedding
words_same <- subset(glv_embedding, rownames(glv_embedding) %in% wrd2vec_embedding$word)

# check words that are in the glove embedding but not in the w2vec embedding 
words_diff <- subset(glv_embedding, !(rownames(glv_embedding) %in% wrd2vec_embedding$word))

# check words that are in the w2v embedding but not in the glove embedding
words_in_w2v_notglve <- subset(w2v_embedding, !( word %in% rownames(glv_embedding)))


# check bigrams embedding
bigrams_embedding <- df_bigrams

# compare the w2v embeddings in which bigrams are and are not included
# check words that are in the w2v bigrams embedding but not in the w2c embedding 
words_diff_w2v <- subset(bigrams_embedding, !(word %in% wrd2vec_embedding$word))
# -> as expected the difference are 209 bigrams

# COMPARE THE GLOBE EMBEDDINGS IN WHICH BIGRAMS ARE AND ARE NOT INCLUDED
words_diff_glove <- subset(glove_embedding_bigrams, !(word %in% rownames(glv_embedding)))

# COMPARE THE W2V and GLOVE EMBEDDINGS INCLUDING BIGRAMS
w2v_bigrams <- readRDS("/Users/amyvanderham/Documents/Research_Assistant_Rgit/veni_sysrev/amy/w2v_bigrams_embedding.RData")

# hard to compare because bigrams are separated on _ in w2v and on _ in glove
words_glovebg_vs_w2vbg <- subset(glove_embedding_bigrams, !(word %in% rownames(w2v_bigrams)))
```

