---
title: "check asreview file"
author: "Amy van der Ham"
output: html_document
editor_options: 
  chunk_output_type: console
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```
Check what the file asreview_result_sysrevemotprob.csv contains. 

```{r}
library(data.table, quietly = TRUE, warn.conflicts = FALSE)

# load .csv file into object 
asreview_results <- read.csv("asreview_result_sysrevemotprob.csv")

# convert object into data table
asreview_results <- as.data.table(asreview_results)

# explore included column and other columns from asreview
unique(asreview_results$included)
summary(as.factor(asreview_results$included))
asreview_results[, c('included', 'asreview_ranking', 'record_id')]
max(asreview_results$asreview_ranking)

# check to recs file that is used in analysis to compare
recs <- read.csv("recs_final.csv")

# convert object into data table
recs <- as.data.table(recs)

# try to merge the datasets 
total <- merge(asreview_results, recs, by="doi")
summary(as.factor(total$included))

# -> if I merge the two datasets all the documents that were coded with a 1 (i.e. relevant/included) in the column included are dropped as well as so articles that had the value NA on the variable included? 

# check combinaties van columns notes, rayyan, excluded_rayyan en included
# unique combinaties voor records die op de variable notes included zijn geassigned 
unique(total[total$notes ==  " RAYYAN-INCLUSION: {\"Caspar\"=>\"Included\"}", c("rayyan", "excluded_rayyan", "included")])

# unique combinaties voor records die op de variable notes Excluded zijn geassigned 
unique(asreview_results[asreview_results$notes ==  " RAYYAN-INCLUSION: {\"Caspar\"=>\"Excluded\"}", c("rayyan", "excluded_rayyan", "included")])

# unique combinaties voor records die op de variable included 1 zijn geassigned
unique(asreview_results[asreview_results$included == 1, c("notes", "rayyan", "excluded_rayyan")])

# unique combinaties voor records die op de variable included 0 zijn geassigned
unique(asreview_results[asreview_results$included == 0, c("notes", "rayyan", "excluded_rayyan")])

# check unique values for recs bestand (eind selectie)
unique(total$excluded_rayyan)
unique(total$included)
unique(total$rayyan)
is.na(asreview_results$included)
```
CONCLUSION: Caspar heeft uitgelegd dat in dit geval 1 juist staat voor excluded asreview en 0 included asreview. 

```{r}
# now that I know that I want to check on what criteria the 12 other observations are deleted. Expect this to be based on rayyan = False and included = na but this is does not seem to be the case looking at the criteria below. 
unique(asreview_results[is.na(asreview_results$included), c("notes", "rayyan", "excluded_rayyan")])

criteria <- asreview_results[asreview_results$rayyan == "False", ]

summary(as.factor(criteria$included))

# need to check this out. Look at manuscript line 792 screening
```


Check information from simulation run in terminal with data set 
```{r}
# terminal: The following records are prior knowledge:
asreview_results[asreview_results$authors ==  "CHERRY KE and GERSTEIN ED and CICIOLLA L", c("included", "title")]

asreview_results[asreview_results$authors ==  "PARSONS SK and BARLOW SE and LEVY SL and SUPRAN SE and KAPLAN SH", c("included", "title")]
```

