---
title: "asreview simulation file"
author: "Amy van der Ham"
date: "9/13/2021"
output: html_document
  chunk_output_type: console
editor_options: 
  chunk_output_type: console
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```
To use the simulation mode in ASReview I need a fully labelled dataset. Which contains a column called included in which records that are relevant are labelled with 1 and records that are irrelevant are labelled with 0. 

```{r}
library(data.table, quietly = TRUE, warn.conflicts = FALSE)
library(dplyr)

# load file with all the records that are screened in asreview into object
asreview_results <- read.csv("asreview_result_sysrevemotprob.csv")

# convert object into data table
asreview_results <- as.data.table(asreview_results)

# load file with the final records that are used in the paper into object
recs <- read.csv("recs_final.csv")
# NOTE: all these files need to be labelled with 1 in the column included because these are the records that were deemed suitable for the analysis. 

# convert object into data table
recs <- as.data.table(recs)

# create new dataframe called asreview_sim to which a new column can be added
asreview_sim <- recs

# add the column included
asreview_sim$included <- 1
summary(as.factor(asreview_sim$included))
# -> all these records now have the value 1 on the variable included

# revert coding in asreview_results as Caspar mentioned that these are reversed coded
asreview_results_rev <- asreview_results
asreview_results_rev$included <- ifelse(asreview_results$included == 0, 1, 0)

# check recoding went correctly by comparing the two datasets
summary(as.factor(asreview_results$included))
summary(as.factor(asreview_results_rev$included))

# now that the records coded 0 in the dataset asreview_result_rev indeed represent the articles that were excluded we can subset these and add them to the dataframe asreview_sim 
subset_irrelevant <- dplyr::filter(asreview_results_rev, included == 0)

# select only those columns that are also in the asreview_sim dataframe
subset_irr <- subset_irrelevant[ ,c("PT", "AU", "AF", "TI", "SO", "LA", "DT", "DE", "ID", "AB", "C1", "RP", "EM", "FU", "FX", "NR", "TC", "Z9", "U1", "U2", "PU", "PI", "PA", "SN", "EI", "J9", "JI", "PD", "PY", "VL", "IS", "AR", "DI", "PG", "WC", "SC", "GA", "UT", "PM", "OA", "DA", "ER", "BP", "EP", "EA", "OI", "RI", "SI", "SU", "MA", "CA", "CT", "CY", "CL", "SP", "EF", "HC", "HP", "PN", "BE", "SE", "BN", "HO", "D2", "DB", "CR", "AU_UN", "AU1_UN", "AU_UN_NR", "SR_FULL", "SR", "doi", "title", "n_duplicates", "included")]

# merge the two dataframes 
asreview_simulation <- rbind(asreview_sim, subset_irr)
# Note: there are 6583 observations. This is 12 less than the in the asreview_result_sysrevemotprob.csv file. Have to check reason for this in exploration_asreviewresultsfile.Rmd. Probably something to do with rayyan. It does not really matter that these cases are excluded for the simulation however. 

# check how many records are coded relevant 1 and irrelevant 0 in the final dataframe
summary(as.factor(asreview_simulation$included))

# save the dataframe
write.csv(asreview_simulation, "/Users/amyvanderham/Documents/Research_Assistant_Rgit/veni_sysrev/asreview_simulation/asreview_simulation.csv", row.names = FALSE)
```



