---
title: "Cluster analysis"
Author: "Amy van der Ham"
date: "10/7/2021"
output: html_document
editor_options: 
  chunk_output_type: console
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
# load libraries
library(dplyr)
library(cluster)
library(ggplot2)
library(devtools)
```

# load data frame with word vector embeddings
```{r}
# load data frame with word vectors into object
df <- readRDS("featurematrix_asreview.RData")

# load data frame with column with selection of words to include in analysis
df_include <- readRDS("include_these2.RData")

# filter the df so that only the words that we want to be included are left
df_final <- df[df_include$include_these, ]

# check how many NA's there are 
summary(df_final)
sum(is.na(df_final$dim2))
# -> we see that there are 2554 rows with a missing val

# drop all words that were in the include these object but not in the word embedding data frame
df_final1 <- na.omit(df_final)
# number of observations makes sense 15274 (words that can be include) - 2554 (number of missings (not in the feature matrix of those 15274 include_these words)) = 12720 observations 
length(unique(rownames(df_final1)))

# check words that should be included but are not in the data frame with the words embeddings and therefore lost. 
df_lost <- subset(df_include, !(include_these2 %in% rownames(df_final1)))
# -> you would expect this number of observations to be 2554 and not 3268....

# check which of these words in that are in df_lost but are also in df_final1
df_mismatch <- df_final1[df_lost$include_these2, ]

# other way to check words that are not included
# feature matrix df with column words
df_check <- df
df_check$words <- row.names(df_check)

# include dataframe change column name to words
df_add <- df_include
names(df_add)[names(df_add) == 'include_these2'] <- 'words'

# add column mismatch in which a row gets a value 0 if the word of that row is in the feature matrix data frame but not in the include(add) data frame. 
df_check$mismatch <- ifelse(df_check$words %in% df_add$words, 1, 0)

summary(as.factor(df_check$mismatch))


df_check$mismatch2 <- ifelse(df_check$words %in% rownames(df_final1), 1, 0)

df_check[df_check$mismatch == 0 & df_check$words %in% rownames(df_final1), "words"]

summary(as.factor(df_check$mismatch2))
```
